#!/bin/bash
#SBATCH --job-name=dpo-cond
#SBATCH --time=10:00:00
#SBATCH --mem=64GB
#SBATCH --partition=gpu
#SBATCH --gpus-per-node=a100:1
#SBATCH --output=logs/slurm/%x-%j.out

set -euo pipefail

module purge
module load Python/3.12.3-GCCcore-13.3.0
module load CUDA/13.2.0

PROJECT_ROOT="${PROJECT_ROOT:-${SLURM_SUBMIT_DIR:-$PWD}}"
cd "${PROJECT_ROOT}"

source .venv/bin/activate
if [ -f "${HOME}/.wandb_secrets" ]; then
  # shellcheck disable=SC1090
  source "${HOME}/.wandb_secrets"
fi

export PYTHONUNBUFFERED=1
export HF_HUB_CACHE="${HF_HUB_CACHE:-/scratch/${USER}/huggingface_cache}"

STAGE="${STAGE:-}"
if [ -z "${STAGE}" ]; then
  echo "ERROR: STAGE is required."
  echo "Valid STAGE values: canonical | hard_dpo | judge_dpo | judge_gptoss | judge_standalone_dpo | judge_decent_dpo | union_decent_dpo | judge_union_dpo"
  exit 1
fi

# ---------------------------------------------------------------------------
# Shared defaults (override via sbatch --export)
# ---------------------------------------------------------------------------
BASE_MODEL="${BASE_MODEL:-meta-llama/Llama-3.1-8B-Instruct}"
BASE_SFT_ADAPTER="${BASE_SFT_ADAPTER:-trained_models/causal/hyperparam_sweep/lr_5e-05_e_5_adapter}"
JUDGE_MODEL="${JUDGE_MODEL:-openai/gpt-oss-120b}"
# GPT-OSS 120B is natively 4-bit quantized; fits on a single RTX 6000 Pro (96 GB VRAM)
JUDGE_TENSOR_PARALLEL="${JUDGE_TENSOR_PARALLEL:-1}"
JUDGE_GPU_TYPE="${JUDGE_GPU_TYPE:-rtx_pro_6000}"

SEED="${SEED:-22}"
TEMPERATURE="${TEMPERATURE:-0.8}"
K_SAMPLES="${K_SAMPLES:-5}"
MAX_MODEL_LEN="${MAX_MODEL_LEN:-4096}"
EPOCHS="${EPOCHS:-2}"
LEARNING_RATE="${LEARNING_RATE:-5e-5}"
BATCH_SIZE="${BATCH_SIZE:-2}"
GRAD_ACCUM="${GRAD_ACCUM:-8}"
DPO_BETA="${DPO_BETA:-0.5}"
HARMFUL_WEIGHT="${HARMFUL_WEIGHT:-1.0}"
UNBALANCED="${UNBALANCED:-0}"
FORCE="${FORCE:-0}"
FORCE_FROM="${FORCE_FROM:-}"
ATN_IMPL="${ATN_IMPL:-sdpa}"

WANDB_PROJECT="${WANDB_PROJECT:-intention-jailbreak}"
WANDB_PROJECT_SFT="${WANDB_PROJECT_SFT:-sft-hyperparam-sweep}"

# Condition paths
HARD_PAIRS_DIR="${HARD_PAIRS_DIR:-data/dpo_pairs/hard}"
HARD_BALANCED_DIR="${HARD_BALANCED_DIR:-data/dpo_pairs/hard_balanced}"
HARD_DPO_OUTPUT="${HARD_DPO_OUTPUT:-trained_models/causal/dpo-hard}"
SFT_PRED_DIR_HARD="${SFT_PRED_DIR_HARD:-data/predictions/sft_hard}"

# Canonical T=0.8 samples shared across all conditions for fair comparison.
# All conditions reuse these samples so only the filtering logic differs.
CANONICAL_SAMPLES="${CANONICAL_SAMPLES:-data/dpo_pairs/train_t0.8/parsed_samples.jsonl}"

JUDGE_PAIRS_DIR="${JUDGE_PAIRS_DIR:-data/dpo_pairs/judge}"
JUDGE_BALANCED_DIR="${JUDGE_BALANCED_DIR:-data/dpo_pairs/judge_balanced}"
JUDGE_DPO_OUTPUT="${JUDGE_DPO_OUTPUT:-trained_models/causal/dpo-judge}"
SFT_PRED_DIR_JUDGE="${SFT_PRED_DIR_JUDGE:-data/predictions/sft_judge}"
# Override epochs/beta for judge independently of the global EPOCHS/DPO_BETA.
# Falls back to global values when not set or empty.
JUDGE_EPOCHS="${JUDGE_EPOCHS:=${EPOCHS}}"
JUDGE_BETA="${JUDGE_BETA:=${DPO_BETA}}"
# Set to non-empty to skip sample generation and reuse cached parsed_samples.jsonl
JUDGE_FROM_SAMPLES="${JUDGE_FROM_SAMPLES:-}"

# judge_standalone_dpo: judge bad_match rejecteds only (no hard mislabels)
JUDGE_STANDALONE_PAIRS_DIR="${JUDGE_STANDALONE_PAIRS_DIR:-data/dpo_pairs/judge_standalone}"
JUDGE_STANDALONE_BALANCED_DIR="${JUDGE_STANDALONE_BALANCED_DIR:-data/dpo_pairs/judge_standalone_balanced}"
JUDGE_STANDALONE_DPO_OUTPUT="${JUDGE_STANDALONE_DPO_OUTPUT:-trained_models/causal/dpo-judge-standalone}"
SFT_PRED_DIR_JUDGE_STANDALONE="${SFT_PRED_DIR_JUDGE_STANDALONE:-data/predictions/sft_judge_standalone}"

# judge_decent_dpo: judge-only with bad_match + decent_match rejecteds
# Reuses pairs generated by judge_standalone_dpo (dpo_pairs_decent.jsonl)
JUDGE_DECENT_BALANCED_DIR="${JUDGE_DECENT_BALANCED_DIR:-data/dpo_pairs/judge_decent_balanced}"
JUDGE_DECENT_DPO_OUTPUT="${JUDGE_DECENT_DPO_OUTPUT:-trained_models/causal/dpo-judge-decent}"
SFT_PRED_DIR_JUDGE_DECENT="${SFT_PRED_DIR_JUDGE_DECENT:-data/predictions/sft_judge_decent}"

# union_decent_dpo: hard ∪ judge (bad_match + decent_match)
# Reuses pairs generated by judge_dpo (dpo_pairs_decent.jsonl)
UNION_DECENT_BALANCED_DIR="${UNION_DECENT_BALANCED_DIR:-data/dpo_pairs/union_decent_balanced}"
UNION_DECENT_DPO_OUTPUT="${UNION_DECENT_DPO_OUTPUT:-trained_models/causal/dpo-union-decent}"
SFT_PRED_DIR_UNION_DECENT="${SFT_PRED_DIR_UNION_DECENT:-data/predictions/sft_union_decent}"

# judge_union_dpo: union of bad_match verdicts from two judge models (gemma + GPT-OSS).
# Requires both judge_dpo and judge_gptoss runs to have completed (need judge_verdict
# saved in their parsed_samples.jsonl). Primary judge dir is JUDGE_PAIRS_DIR (gemma);
# second judge dir is JUDGE_GPTOSS_PAIRS_DIR (GPT-OSS).
JUDGE_GPTOSS_PAIRS_DIR="${JUDGE_GPTOSS_PAIRS_DIR:-data/dpo_pairs/judge_gptoss}"
JUDGE_UNION_PAIRS_DIR="${JUDGE_UNION_PAIRS_DIR:-data/dpo_pairs/judge_union}"
JUDGE_UNION_BALANCED_DIR="${JUDGE_UNION_BALANCED_DIR:-data/dpo_pairs/judge_union_balanced}"
JUDGE_UNION_DPO_OUTPUT="${JUDGE_UNION_DPO_OUTPUT:-trained_models/causal/dpo-judge-union}"
SFT_PRED_DIR_JUDGE_UNION="${SFT_PRED_DIR_JUDGE_UNION:-data/predictions/sft_judge_union}"

echo "======================================================================"
echo " Preference Condition Stage"
echo "  Stage       : ${STAGE}"
echo "  Project root: ${PROJECT_ROOT}"
echo "  Base model  : ${BASE_MODEL}"
echo "======================================================================"

PIPELINE_RESTART_ARGS=()
if [ "${FORCE}" = "1" ]; then
  PIPELINE_RESTART_ARGS+=(--force)
fi
if [ -n "${FORCE_FROM}" ]; then
  PIPELINE_RESTART_ARGS+=(--force-from "${FORCE_FROM}")
fi

case "${STAGE}" in
  canonical)
    # Generate shared T=0.8 samples once. Every other condition uses
    # --from-samples pointing here so they never re-run the SFT model.
    if [ -f "${CANONICAL_SAMPLES}" ]; then
      echo "[SKIP] Canonical samples already exist at ${CANONICAL_SAMPLES}"
      exit 0
    fi
    # Derive output dir from CANONICAL_SAMPLES path
    CANONICAL_OUT_DIR="$(dirname "${CANONICAL_SAMPLES}")"
    python scripts/dpo/generate_dpo_pairs.py \
      --adapter-path "${BASE_SFT_ADAPTER}" \
      --base-model "${BASE_MODEL}" \
      --output-dir "${CANONICAL_OUT_DIR}" \
      --num-samples "${K_SAMPLES}" \
      --temperature "${TEMPERATURE}" \
      --max-model-len "${MAX_MODEL_LEN}" \
      --seed "${SEED}"
    ;;

  hard_dpo)
    HARD_SKIP_STEPS="6"
    HARD_EXTRA_ARGS=()
    if [ "${UNBALANCED}" = "1" ]; then
      # Skip balancing step; use harmful_weight in loss instead
      HARD_SKIP_STEPS="2,6"
      HARD_EXTRA_ARGS+=(--unbalanced --harmful-weight "${HARMFUL_WEIGHT}")
    fi
    python scripts/dpo/run_preference_pipeline.py \
      --adapter-path "${BASE_SFT_ADAPTER}" \
      --base-model "${BASE_MODEL}" \
      --pairs-dir "${HARD_PAIRS_DIR}" \
      --balanced-pairs-dir "${HARD_BALANCED_DIR}" \
      --dpo-output-dir "${HARD_DPO_OUTPUT}" \
      --sft-pred-dir "${SFT_PRED_DIR_HARD}" \
      --from-samples "${CANONICAL_SAMPLES}" \
      --temperature "${TEMPERATURE}" \
      --k-samples "${K_SAMPLES}" \
      --max-model-len "${MAX_MODEL_LEN}" \
      --epochs "${EPOCHS}" \
      --learning-rate "${LEARNING_RATE}" \
      --batch-size "${BATCH_SIZE}" \
      --grad-accum "${GRAD_ACCUM}" \
      --dpo-beta "${DPO_BETA}" \
      --seed "${SEED}" \
      --wandb-project "${WANDB_PROJECT}" \
      "${PIPELINE_RESTART_ARGS[@]}" \
      "${HARD_EXTRA_ARGS[@]}" \
      --skip-steps "${HARD_SKIP_STEPS}"
    ;;

  judge_dpo)
    # Two-pass judge flow.
    # Pass 1: always reuse canonical T=0.8 samples (generated once by hard_dpo or
    # train_t0.8 stage) so all conditions start from identical base samples.
    # JUDGE_FROM_SAMPLES is kept for backwards compatibility but is now redundant
    # since we always point at CANONICAL_SAMPLES.
    if [ -z "${JUDGE_FROM_SAMPLES}" ]; then
      echo "[judge_dpo] Reusing canonical samples from ${CANONICAL_SAMPLES}"
    else
      echo "[judge_dpo] JUDGE_FROM_SAMPLES set — reusing ${JUDGE_PAIRS_DIR}/parsed_samples.jsonl"
    fi

    python scripts/dpo/generate_dpo_pairs.py \
      --from-samples "${CANONICAL_SAMPLES}" \
      --adapter-path "${BASE_SFT_ADAPTER}" \
      --base-model "${BASE_MODEL}" \
      --output-dir "${JUDGE_PAIRS_DIR}" \
      --intent-filter \
      --judge-model "${JUDGE_MODEL}" \
      --judge-tensor-parallel "${JUDGE_TENSOR_PARALLEL}" \
      --max-model-len "${MAX_MODEL_LEN}"

    python scripts/dpo/run_preference_pipeline.py \
      --adapter-path "${BASE_SFT_ADAPTER}" \
      --base-model "${BASE_MODEL}" \
      --pairs-dir "${JUDGE_PAIRS_DIR}" \
      --balanced-pairs-dir "${JUDGE_BALANCED_DIR}" \
      --dpo-output-dir "${JUDGE_DPO_OUTPUT}" \
      --sft-pred-dir "${SFT_PRED_DIR_JUDGE}" \
      --epochs "${JUDGE_EPOCHS}" \
      --learning-rate "${LEARNING_RATE}" \
      --batch-size "${BATCH_SIZE}" \
      --grad-accum "${GRAD_ACCUM}" \
      --dpo-beta "${JUDGE_BETA}" \
      --seed "${SEED}" \
      --wandb-project "${WANDB_PROJECT}" \
      "${PIPELINE_RESTART_ARGS[@]}" \
      --skip-steps 1,6
    ;;

  judge_gptoss)
    # Same flow as judge_dpo but using GPT-OSS as the judge model.
    # Outputs to JUDGE_GPTOSS_PAIRS_DIR so judge_union_dpo can merge verdicts.
    # GPT-OSS 120B needs the RTX Pro 6000 (96 GB) — override GPU at submit time if needed.
    GPTOSS_JUDGE_MODEL="${GPTOSS_JUDGE_MODEL:-openai/gpt-oss-120b}"
    GPTOSS_JUDGE_TP="${GPTOSS_JUDGE_TP:-1}"

    python scripts/dpo/generate_dpo_pairs.py \
      --from-samples "${CANONICAL_SAMPLES}" \
      --adapter-path "${BASE_SFT_ADAPTER}" \
      --base-model "${BASE_MODEL}" \
      --output-dir "${JUDGE_GPTOSS_PAIRS_DIR}" \
      --intent-filter \
      --judge-model "${GPTOSS_JUDGE_MODEL}" \
      --judge-tensor-parallel "${GPTOSS_JUDGE_TP}" \
      --max-model-len "${MAX_MODEL_LEN}"

    python scripts/dpo/run_preference_pipeline.py \
      --adapter-path "${BASE_SFT_ADAPTER}" \
      --base-model "${BASE_MODEL}" \
      --pairs-dir "${JUDGE_GPTOSS_PAIRS_DIR}" \
      --balanced-pairs-dir "${JUDGE_UNION_BALANCED_DIR/_balanced/_gptoss_balanced}" \
      --dpo-output-dir "trained_models/causal/dpo-judge-gptoss" \
      --sft-pred-dir "data/predictions/sft_judge_gptoss" \
      --epochs "${JUDGE_EPOCHS}" \
      --learning-rate "${LEARNING_RATE}" \
      --batch-size "${BATCH_SIZE}" \
      --grad-accum "${GRAD_ACCUM}" \
      --dpo-beta "${JUDGE_BETA}" \
      --seed "${SEED}" \
      --wandb-project "${WANDB_PROJECT}" \
      "${PIPELINE_RESTART_ARGS[@]}" \
      --skip-steps 1,6
    ;;

  judge_standalone_dpo)
    # Judge-only condition: rejecteds = bad_match samples only, no hard mislabels.
    # Generates both dpo_pairs.jsonl (bad only) and dpo_pairs_decent.jsonl (bad+decent)
    # so judge_decent_dpo can reuse these pairs without a second generation pass.
    python scripts/dpo/generate_dpo_pairs.py \
      --from-samples "${CANONICAL_SAMPLES}" \
      --adapter-path "${BASE_SFT_ADAPTER}" \
      --base-model "${BASE_MODEL}" \
      --output-dir "${JUDGE_STANDALONE_PAIRS_DIR}" \
      --intent-filter \
      --judge-only \
      --judge-model "${JUDGE_MODEL}" \
      --judge-tensor-parallel "${JUDGE_TENSOR_PARALLEL}" \
      --max-model-len "${MAX_MODEL_LEN}"

    python scripts/dpo/run_preference_pipeline.py \
      --adapter-path "${BASE_SFT_ADAPTER}" \
      --base-model "${BASE_MODEL}" \
      --pairs-dir "${JUDGE_STANDALONE_PAIRS_DIR}" \
      --balanced-pairs-dir "${JUDGE_STANDALONE_BALANCED_DIR}" \
      --dpo-output-dir "${JUDGE_STANDALONE_DPO_OUTPUT}" \
      --sft-pred-dir "${SFT_PRED_DIR_JUDGE_STANDALONE}" \
      --epochs "${JUDGE_EPOCHS}" \
      --learning-rate "${LEARNING_RATE}" \
      --batch-size "${BATCH_SIZE}" \
      --grad-accum "${GRAD_ACCUM}" \
      --dpo-beta "${JUDGE_BETA}" \
      --seed "${SEED}" \
      --wandb-project "${WANDB_PROJECT}" \
      "${PIPELINE_RESTART_ARGS[@]}" \
      --skip-steps 1,6
    ;;

  judge_decent_dpo)
    # Judge-only condition with bad_match + decent_match rejecteds.
    # Requires judge_standalone_dpo to have run first (reuses its dpo_pairs_decent.jsonl).
    python scripts/dpo/run_preference_pipeline.py \
      --adapter-path "${BASE_SFT_ADAPTER}" \
      --base-model "${BASE_MODEL}" \
      --pairs-dir "${JUDGE_STANDALONE_PAIRS_DIR}" \
      --pairs-filename "dpo_pairs_decent.jsonl" \
      --balanced-pairs-dir "${JUDGE_DECENT_BALANCED_DIR}" \
      --dpo-output-dir "${JUDGE_DECENT_DPO_OUTPUT}" \
      --sft-pred-dir "${SFT_PRED_DIR_JUDGE_DECENT}" \
      --epochs "${JUDGE_EPOCHS}" \
      --learning-rate "${LEARNING_RATE}" \
      --batch-size "${BATCH_SIZE}" \
      --grad-accum "${GRAD_ACCUM}" \
      --dpo-beta "${JUDGE_BETA}" \
      --seed "${SEED}" \
      --wandb-project "${WANDB_PROJECT}" \
      "${PIPELINE_RESTART_ARGS[@]}" \
      --skip-steps 1,6
    ;;

  union_decent_dpo)
    # Union condition with bad_match + decent_match rejecteds (hard ∪ judge decent).
    # Requires judge_dpo to have run first (reuses its dpo_pairs_decent.jsonl).
    python scripts/dpo/run_preference_pipeline.py \
      --adapter-path "${BASE_SFT_ADAPTER}" \
      --base-model "${BASE_MODEL}" \
      --pairs-dir "${JUDGE_PAIRS_DIR}" \
      --pairs-filename "dpo_pairs_decent.jsonl" \
      --balanced-pairs-dir "${UNION_DECENT_BALANCED_DIR}" \
      --dpo-output-dir "${UNION_DECENT_DPO_OUTPUT}" \
      --sft-pred-dir "${SFT_PRED_DIR_UNION_DECENT}" \
      --epochs "${JUDGE_EPOCHS}" \
      --learning-rate "${LEARNING_RATE}" \
      --batch-size "${BATCH_SIZE}" \
      --grad-accum "${GRAD_ACCUM}" \
      --dpo-beta "${JUDGE_BETA}" \
      --seed "${SEED}" \
      --wandb-project "${WANDB_PROJECT}" \
      "${PIPELINE_RESTART_ARGS[@]}" \
      --skip-steps 1,6
    ;;

  judge_union_dpo)
    # Union of bad_match verdicts from two judge models (gemma + GPT-OSS).
    # No model inference needed — verdicts are loaded from cached parsed_samples.jsonl.
    # Prerequisites: judge_dpo and judge_gptoss must have completed so that
    # judge_verdict fields are saved in their parsed_samples.jsonl.

    JUDGE_PRIMARY_SAMPLES="${JUDGE_PAIRS_DIR}/parsed_samples.jsonl"
    JUDGE_GPTOSS_SAMPLES="${JUDGE_GPTOSS_PAIRS_DIR}/parsed_samples.jsonl"

    if [ ! -f "${JUDGE_PRIMARY_SAMPLES}" ]; then
      echo "ERROR: ${JUDGE_PRIMARY_SAMPLES} not found."
      echo "  Run judge_dpo (gemma) first to generate judge verdicts."
      exit 1
    fi
    if [ ! -f "${JUDGE_GPTOSS_SAMPLES}" ]; then
      echo "ERROR: ${JUDGE_GPTOSS_SAMPLES} not found."
      echo "  Run judge_gptoss first to generate judge verdicts."
      exit 1
    fi

    # Check that judge_verdict is actually present in both files
    python3 -c "
import json, sys
for path in ['${JUDGE_PRIMARY_SAMPLES}', '${JUDGE_GPTOSS_SAMPLES}']:
    lines = open(path).readlines()
    found = sum(1 for l in lines for s in json.loads(l).get('samples', []) if 'judge_verdict' in s)
    if found == 0:
        print(f'ERROR: judge_verdict missing from {path}')
        print('  Re-run the judge stage with the updated code to cache verdicts.')
        sys.exit(1)
    print(f'OK: {path} — {found} samples with judge_verdict')
print('Prerequisite check passed.')
" || exit 1

    # Merge verdicts and build pairs (no model loaded — verdicts already cached)
    python scripts/dpo/generate_dpo_pairs.py \
      --from-samples "${JUDGE_PRIMARY_SAMPLES}" \
      --adapter-path "${BASE_SFT_ADAPTER}" \
      --base-model "${BASE_MODEL}" \
      --output-dir "${JUDGE_UNION_PAIRS_DIR}" \
      --intent-filter \
      --union-judge-dir "${JUDGE_GPTOSS_PAIRS_DIR}" \
      --max-model-len "${MAX_MODEL_LEN}"

    python scripts/dpo/run_preference_pipeline.py \
      --adapter-path "${BASE_SFT_ADAPTER}" \
      --base-model "${BASE_MODEL}" \
      --pairs-dir "${JUDGE_UNION_PAIRS_DIR}" \
      --balanced-pairs-dir "${JUDGE_UNION_BALANCED_DIR}" \
      --dpo-output-dir "${JUDGE_UNION_DPO_OUTPUT}" \
      --sft-pred-dir "${SFT_PRED_DIR_JUDGE_UNION}" \
      --epochs "${JUDGE_EPOCHS}" \
      --learning-rate "${LEARNING_RATE}" \
      --batch-size "${BATCH_SIZE}" \
      --grad-accum "${GRAD_ACCUM}" \
      --dpo-beta "${JUDGE_BETA}" \
      --seed "${SEED}" \
      --wandb-project "${WANDB_PROJECT}" \
      "${PIPELINE_RESTART_ARGS[@]}" \
      --skip-steps 1,6
    ;;

  *)
    echo "ERROR: Unknown STAGE='${STAGE}'"
    exit 2
    ;;
esac

echo ""
echo "Stage ${STAGE} completed."
