#!/bin/bash
#SBATCH --job-name=dpo-cond
#SBATCH --time=02:00:00
#SBATCH --mem=32GB
#SBATCH --partition=gpu
#SBATCH --gpus-per-node=a100:1
#SBATCH --output=logs/slurm/%x-%j.out

set -euo pipefail

module --force purge
module load Python/3.12.3-GCCcore-13.3.0
module load CUDA/13.2.0

PROJECT_ROOT="${PROJECT_ROOT:-${SLURM_SUBMIT_DIR:-$PWD}}"
cd "${PROJECT_ROOT}"

source .venv/bin/activate
if [ -f "${HOME}/.wandb_secrets" ]; then
  # shellcheck disable=SC1090
  source "${HOME}/.wandb_secrets"
fi

export PYTHONUNBUFFERED=1
export HF_HUB_CACHE="${HF_HUB_CACHE:-/scratch/${USER}/huggingface_cache}"
# Reproducibility controls (can be overridden via sbatch --export)
export PYTHONHASHSEED="${PYTHONHASHSEED:-0}"
export CUBLAS_WORKSPACE_CONFIG="${CUBLAS_WORKSPACE_CONFIG:-:4096:8}"
export TOKENIZERS_PARALLELISM="${TOKENIZERS_PARALLELISM:-false}"
export CUDA_LAUNCH_BLOCKING="${CUDA_LAUNCH_BLOCKING:-0}"

STAGE="${STAGE:-}"
if [ -z "${STAGE}" ]; then
  echo "ERROR: STAGE is required."
  echo "Valid STAGE values: canonical | hard_dpo | judge_dpo | judge_gptoss | judge_standalone_dpo | judge_gptoss_standalone_dpo | judge_decent_dpo | union_decent_dpo | judge_union_dpo | ood_eval | ratio_dpo | curriculum_dpo | gemma_canonical | gemma_hard_dpo"
  exit 1
fi

# ---------------------------------------------------------------------------
# Shared defaults (override via sbatch --export)
# ---------------------------------------------------------------------------
BASE_MODEL="${BASE_MODEL:-meta-llama/Llama-3.1-8B-Instruct}"
BASE_SFT_ADAPTER="${BASE_SFT_ADAPTER:-Jazhyc/llama-3.1-8b-sft-generation}"
JUDGE_MODEL="${JUDGE_MODEL:-openai/gpt-oss-120b}"
JUDGE_MODEL_SLUG="${JUDGE_MODEL_SLUG:-${JUDGE_MODEL//\//_}}"
JUDGE_TENSOR_PARALLEL="${JUDGE_TENSOR_PARALLEL:-1}"
JUDGE_GPU_TYPE="${JUDGE_GPU_TYPE:-rtx_pro_6000}"

SEED="${SEED:-22}"
TEMPERATURE="${TEMPERATURE:-0.8}"
K_SAMPLES="${K_SAMPLES:-5}"
MAX_MODEL_LEN="${MAX_MODEL_LEN:-4096}"
EPOCHS="${EPOCHS:-2}"
LEARNING_RATE="${LEARNING_RATE:-5e-5}"
BATCH_SIZE="${BATCH_SIZE:-2}"
GRAD_ACCUM="${GRAD_ACCUM:-8}"
DPO_BETA="${DPO_BETA:-0.5}"
DPO_SAVE_STRATEGY="${DPO_SAVE_STRATEGY:-no}"
DPO_SAVE_STEPS="${DPO_SAVE_STEPS:-200}"
DPO_SAVE_TOTAL_LIMIT="${DPO_SAVE_TOTAL_LIMIT:-2}"
SELECT_BEST_OOD_CHECKPOINT="${SELECT_BEST_OOD_CHECKPOINT:-0}"
OOD_EVAL_GPU_MEMORY_UTILIZATION="${OOD_EVAL_GPU_MEMORY_UTILIZATION:-0.75}"
HARMFUL_WEIGHT="${HARMFUL_WEIGHT:-1.0}"
UNBALANCED="${UNBALANCED:-0}"
FORCE="${FORCE:-0}"
FORCE_FROM="${FORCE_FROM:-}"
ATTN_IMPL="${ATTN_IMPL:-sdpa}"
EVAL_LORA_RANK="${EVAL_LORA_RANK:-16}"

WANDB_PROJECT="${WANDB_PROJECT:-intention-jailbreak}"
# For ood_eval stage: path to the trained DPO adapter to evaluate.
# Set to the _adapter directory of whichever condition you want to assess.
OOD_EVAL_ADAPTER="${OOD_EVAL_ADAPTER:-}"
OOD_EVAL_OUTPUT="${OOD_EVAL_OUTPUT:-data/safety_experiment/ood_validation/dpo}"

# Condition paths
HARD_PAIRS_DIR="${HARD_PAIRS_DIR:-data/dpo_pairs/hard}"
HARD_BALANCED_DIR="${HARD_BALANCED_DIR:-data/dpo_pairs/hard_balanced}"
HARD_DPO_OUTPUT="${HARD_DPO_OUTPUT:-trained_models/causal/dpo-hard}"
# Canonical T=0.8 samples shared across all conditions for fair comparison.
# All conditions reuse these samples so only the filtering logic differs.
CANONICAL_SAMPLES="${CANONICAL_SAMPLES:-data/dpo_pairs/train_t0.8/parsed_samples.jsonl}"

JUDGE_PAIRS_DIR="${JUDGE_PAIRS_DIR:-data/dpo_pairs/judge}"
JUDGE_BALANCED_DIR="${JUDGE_BALANCED_DIR:-data/dpo_pairs/judge_balanced}"
JUDGE_DPO_OUTPUT="${JUDGE_DPO_OUTPUT:-trained_models/causal/dpo-judge}"
# Override epochs/beta for judge independently of the global EPOCHS/DPO_BETA.
# Falls back to global values when not set or empty.
JUDGE_EPOCHS="${JUDGE_EPOCHS:=${EPOCHS}}"
JUDGE_BETA="${JUDGE_BETA:=${DPO_BETA}}"
# Set to non-empty to skip sample generation and reuse cached parsed_samples.jsonl
JUDGE_FROM_SAMPLES="${JUDGE_FROM_SAMPLES:-}"

# judge_standalone_dpo: judge bad_match rejecteds only (no hard mislabels)
JUDGE_STANDALONE_PAIRS_DIR="${JUDGE_STANDALONE_PAIRS_DIR:-data/dpo_pairs/judge_standalone}"
JUDGE_STANDALONE_BALANCED_DIR="${JUDGE_STANDALONE_BALANCED_DIR:-data/dpo_pairs/judge_standalone_balanced}"
JUDGE_STANDALONE_DPO_OUTPUT="${JUDGE_STANDALONE_DPO_OUTPUT:-trained_models/causal/dpo-judge-standalone}"

# judge_decent_dpo: judge-only with bad_match + decent_match rejecteds
# Reuses pairs generated by judge_standalone_dpo (dpo_pairs_decent.jsonl)
JUDGE_DECENT_BALANCED_DIR="${JUDGE_DECENT_BALANCED_DIR:-data/dpo_pairs/judge_decent_balanced}"
JUDGE_DECENT_DPO_OUTPUT="${JUDGE_DECENT_DPO_OUTPUT:-trained_models/causal/dpo-judge-decent}"

# union_decent_dpo: hard ∪ judge (bad_match + decent_match)
# Reuses pairs generated by judge_dpo (dpo_pairs_decent.jsonl)
UNION_DECENT_BALANCED_DIR="${UNION_DECENT_BALANCED_DIR:-data/dpo_pairs/union_decent_balanced}"
UNION_DECENT_DPO_OUTPUT="${UNION_DECENT_DPO_OUTPUT:-trained_models/causal/dpo-union-decent}"

# judge_gptoss_standalone_dpo: GPT-OSS judge bad_match rejecteds only (no hard mislabels).
# GPT-OSS analogue of judge_standalone_dpo, for a clean standalone comparison.
JUDGE_GPTOSS_STANDALONE_PAIRS_DIR="${JUDGE_GPTOSS_STANDALONE_PAIRS_DIR:-data/dpo_pairs/judge_gptoss_standalone}"
JUDGE_GPTOSS_STANDALONE_BALANCED_DIR="${JUDGE_GPTOSS_STANDALONE_BALANCED_DIR:-data/dpo_pairs/judge_gptoss_standalone_balanced}"
JUDGE_GPTOSS_STANDALONE_DPO_OUTPUT="${JUDGE_GPTOSS_STANDALONE_DPO_OUTPUT:-trained_models/causal/dpo-judge-gptoss-standalone}"

# judge_union_dpo: union of bad_match verdicts from two judge models (gemma + GPT-OSS).
# Requires both judge_dpo and judge_gptoss runs to have completed (need judge_verdict
# saved in their parsed_samples.jsonl). Primary judge dir is JUDGE_PAIRS_DIR (gemma);
# second judge dir is JUDGE_GPTOSS_PAIRS_DIR (GPT-OSS).
JUDGE_GPTOSS_PAIRS_DIR="${JUDGE_GPTOSS_PAIRS_DIR:-data/dpo_pairs/judge_gptoss}"
JUDGE_UNION_PAIRS_DIR="${JUDGE_UNION_PAIRS_DIR:-data/dpo_pairs/judge_union}"
JUDGE_UNION_BALANCED_DIR="${JUDGE_UNION_BALANCED_DIR:-data/dpo_pairs/judge_union_balanced}"
JUDGE_UNION_DPO_OUTPUT="${JUDGE_UNION_DPO_OUTPUT:-trained_models/causal/dpo-judge-union}"

# ---------------------------------------------------------------------------
# Ratio sweep variables
# ---------------------------------------------------------------------------
# RATIO: fraction of judge pairs added on top of all hard pairs (0.0–1.0).
# Set per-job via sbatch --export. HARD_PAIRS_FILE and JUDGE_PAIRS_FILE must
# point to the pair sets produced by the canonical hard/judge stages.
RATIO="${RATIO:-0.5}"
RATIO_TAG="${RATIO_TAG:-${RATIO}}"   # e.g. "0.50" for directory names
RATIO_PAIRS_DIR="${RATIO_PAIRS_DIR:-data/dpo_pairs/ratio_${RATIO_TAG}}"
RATIO_BALANCED_DIR="${RATIO_BALANCED_DIR:-data/dpo_pairs/ratio_${RATIO_TAG}_balanced}"
RATIO_DPO_OUTPUT="${RATIO_DPO_OUTPUT:-trained_models/causal/dpo-ratio-${RATIO_TAG}}"
# Pair source files (defaults point to canonical hard/judge pair sets)
HARD_PAIRS_FILE="${HARD_PAIRS_FILE:-${HARD_PAIRS_DIR}/pairs_wrong_only.jsonl}"
JUDGE_PAIRS_FILE="${JUDGE_PAIRS_FILE:-${JUDGE_PAIRS_DIR}/pairs_judge_bad_only.jsonl}"

# ---------------------------------------------------------------------------
# Curriculum training variables
# ---------------------------------------------------------------------------
# Continuation-only curriculum:
#   Start from an existing hard-DPO adapter and continue on judge pairs.
#   Reference stays at SFT (--adapter-path); policy warm-starts from
#   --policy-adapter (CURRICULUM_POLICY_ADAPTER).
PHASE2_EPOCHS="${PHASE2_EPOCHS:-3}"
CURRICULUM_OUTPUT="${CURRICULUM_OUTPUT:-trained_models/causal/dpo-curriculum}"
CURRICULUM_POLICY_ADAPTER="${CURRICULUM_POLICY_ADAPTER:-}"

# ---------------------------------------------------------------------------
# Gemma DPO variables
# ---------------------------------------------------------------------------
GEMMA_BASE_MODEL="${GEMMA_BASE_MODEL:-google/gemma-3-12b-it}"
# Set to the merged SFT model HF ID (full weights) or a LoRA adapter ID.
# If GEMMA_NO_LORA=1 the pair generation step loads the model directly without LoRA.
GEMMA_SFT_ADAPTER="${GEMMA_SFT_ADAPTER:-Jazhyc/gemma-3-12b-intent-jailbreak-classifier-sft}"
GEMMA_NO_LORA="${GEMMA_NO_LORA:-0}"
GEMMA_CANONICAL_SAMPLES="${GEMMA_CANONICAL_SAMPLES:-data/dpo_pairs/gemma_train_t0.8/parsed_samples.jsonl}"
GEMMA_HARD_PAIRS_DIR="${GEMMA_HARD_PAIRS_DIR:-data/dpo_pairs/gemma_hard}"
GEMMA_HARD_BALANCED_DIR="${GEMMA_HARD_BALANCED_DIR:-data/dpo_pairs/gemma_hard_balanced}"
GEMMA_HARD_DPO_OUTPUT="${GEMMA_HARD_DPO_OUTPUT:-trained_models/causal/dpo-gemma-hard}"

echo "======================================================================"
echo " Preference Condition Stage"
echo "  Stage       : ${STAGE}"
echo "  Project root: ${PROJECT_ROOT}"
echo "  Base model  : ${BASE_MODEL}"
echo "======================================================================"

PIPELINE_RESTART_ARGS=()
if [ "${FORCE}" = "1" ]; then
  PIPELINE_RESTART_ARGS+=(--force)
fi
if [ -n "${FORCE_FROM}" ]; then
  PIPELINE_RESTART_ARGS+=(--force-from "${FORCE_FROM}")
fi

PIPELINE_CKPT_ARGS=(
  --dpo-save-strategy "${DPO_SAVE_STRATEGY}"
  --dpo-save-total-limit "${DPO_SAVE_TOTAL_LIMIT}"
)
if [ "${DPO_SAVE_STRATEGY}" = "steps" ]; then
  PIPELINE_CKPT_ARGS+=(--dpo-save-steps "${DPO_SAVE_STEPS}")
fi
if [ "${SELECT_BEST_OOD_CHECKPOINT}" = "1" ]; then
  PIPELINE_CKPT_ARGS+=(--select-best-ood-checkpoint)
  PIPELINE_CKPT_ARGS+=(--ood-eval-gpu-memory-utilization "${OOD_EVAL_GPU_MEMORY_UTILIZATION}")
fi

TRAIN_CKPT_ARGS=(
  --save-strategy "${DPO_SAVE_STRATEGY}"
  --save-total-limit "${DPO_SAVE_TOTAL_LIMIT}"
)
if [ "${DPO_SAVE_STRATEGY}" = "steps" ]; then
  TRAIN_CKPT_ARGS+=(--save-steps "${DPO_SAVE_STEPS}")
fi
if [ "${SELECT_BEST_OOD_CHECKPOINT}" = "1" ]; then
  TRAIN_CKPT_ARGS+=(--select-best-ood-checkpoint)
  TRAIN_CKPT_ARGS+=(--ood-eval-gpu-memory-utilization "${OOD_EVAL_GPU_MEMORY_UTILIZATION}")
fi

case "${STAGE}" in
  canonical)
    # Generate shared T=0.8 samples once. Every other condition uses
    # --from-samples pointing here so they never re-run the SFT model.
    if [ -f "${CANONICAL_SAMPLES}" ]; then
      echo "[SKIP] Canonical samples already exist at ${CANONICAL_SAMPLES}"
      exit 0
    fi
    # Derive output dir from CANONICAL_SAMPLES path
    CANONICAL_OUT_DIR="$(dirname "${CANONICAL_SAMPLES}")"
    python scripts/dpo/generate_dpo_pairs.py \
      --adapter-path "${BASE_SFT_ADAPTER}" \
      --base-model "${BASE_MODEL}" \
      --output-dir "${CANONICAL_OUT_DIR}" \
      --num-samples "${K_SAMPLES}" \
      --temperature "${TEMPERATURE}" \
      --max-model-len "${MAX_MODEL_LEN}" \
      --seed "${SEED}"
    ;;

  hard_dpo)
    HARD_SKIP_STEPS=""
    HARD_EXTRA_ARGS=()
    if [ "${UNBALANCED}" = "1" ]; then
      # Skip balancing step; use harmful_weight in loss instead
      HARD_SKIP_STEPS="2"
      HARD_EXTRA_ARGS+=(--unbalanced --harmful-weight "${HARMFUL_WEIGHT}")
    fi
    python scripts/dpo/run_preference_pipeline.py \
      --adapter-path "${BASE_SFT_ADAPTER}" \
      --base-model "${BASE_MODEL}" \
      --pairs-dir "${HARD_PAIRS_DIR}" \
      --balanced-pairs-dir "${HARD_BALANCED_DIR}" \
      --dpo-output-dir "${HARD_DPO_OUTPUT}" \
      --from-samples "${CANONICAL_SAMPLES}" \
      --temperature "${TEMPERATURE}" \
      --k-samples "${K_SAMPLES}" \
      --max-model-len "${MAX_MODEL_LEN}" \
      --epochs "${EPOCHS}" \
      --learning-rate "${LEARNING_RATE}" \
      --batch-size "${BATCH_SIZE}" \
      --grad-accum "${GRAD_ACCUM}" \
      --dpo-beta "${DPO_BETA}" \
      --attn-implementation "${ATTN_IMPL}" \
      --seed "${SEED}" \
      --wandb-project "${WANDB_PROJECT}" \
      --wandb-run "hard-dpo-beta${DPO_BETA}-seed${SEED}" \
      "${PIPELINE_CKPT_ARGS[@]}" \
      "${PIPELINE_RESTART_ARGS[@]}" \
      "${HARD_EXTRA_ARGS[@]}" \
      ${HARD_SKIP_STEPS:+--skip-steps "${HARD_SKIP_STEPS}"}
    ;;

  judge_dpo)
    # Two-pass judge flow.
    # Pass 1: always reuse canonical T=0.8 samples (generated once by hard_dpo or
    # train_t0.8 stage) so all conditions start from identical base samples.
    # JUDGE_FROM_SAMPLES is kept for backwards compatibility but is now redundant
    # since we always point at CANONICAL_SAMPLES.
    if [ -z "${JUDGE_FROM_SAMPLES}" ]; then
      echo "[judge_dpo] Reusing canonical samples from ${CANONICAL_SAMPLES}"
    else
      echo "[judge_dpo] JUDGE_FROM_SAMPLES set — reusing ${JUDGE_PAIRS_DIR}/parsed_samples.jsonl"
    fi

    python scripts/dpo/generate_dpo_pairs.py \
      --from-samples "${CANONICAL_SAMPLES}" \
      --adapter-path "${BASE_SFT_ADAPTER}" \
      --base-model "${BASE_MODEL}" \
      --output-dir "${JUDGE_PAIRS_DIR}" \
      --intent-filter \
      --judge-model "${JUDGE_MODEL}" \
      --judge-tensor-parallel "${JUDGE_TENSOR_PARALLEL}" \
      --max-model-len "${MAX_MODEL_LEN}"

    python scripts/dpo/run_preference_pipeline.py \
      --adapter-path "${BASE_SFT_ADAPTER}" \
      --base-model "${BASE_MODEL}" \
      --pairs-dir "${JUDGE_PAIRS_DIR}" \
      --balanced-pairs-dir "${JUDGE_BALANCED_DIR}" \
      --dpo-output-dir "${JUDGE_DPO_OUTPUT}" \
      --epochs "${JUDGE_EPOCHS}" \
      --learning-rate "${LEARNING_RATE}" \
      --batch-size "${BATCH_SIZE}" \
      --grad-accum "${GRAD_ACCUM}" \
      --dpo-beta "${JUDGE_BETA}" \
      --attn-implementation "${ATTN_IMPL}" \
      --seed "${SEED}" \
      --wandb-project "${WANDB_PROJECT}" \
      --wandb-run "judge-dpo-${JUDGE_MODEL_SLUG}-beta${JUDGE_BETA}-seed${SEED}" \
      "${PIPELINE_CKPT_ARGS[@]}" \
      "${PIPELINE_RESTART_ARGS[@]}" \
      --skip-steps 1
    ;;

  judge_gptoss)
    # Same flow as judge_dpo but using GPT-OSS as the judge model.
    # Outputs to JUDGE_GPTOSS_PAIRS_DIR so judge_union_dpo can merge verdicts.
    # GPT-OSS 120B needs the RTX Pro 6000 (96 GB) — override GPU at submit time if needed.
    GPTOSS_JUDGE_MODEL="${GPTOSS_JUDGE_MODEL:-openai/gpt-oss-120b}"
    GPTOSS_JUDGE_MODEL_SLUG="${GPTOSS_JUDGE_MODEL//\//_}"
    GPTOSS_JUDGE_TP="${GPTOSS_JUDGE_TP:-1}"

    python scripts/dpo/generate_dpo_pairs.py \
      --from-samples "${CANONICAL_SAMPLES}" \
      --adapter-path "${BASE_SFT_ADAPTER}" \
      --base-model "${BASE_MODEL}" \
      --output-dir "${JUDGE_GPTOSS_PAIRS_DIR}" \
      --intent-filter \
      --judge-model "${GPTOSS_JUDGE_MODEL}" \
      --judge-tensor-parallel "${GPTOSS_JUDGE_TP}" \
      --max-model-len "${MAX_MODEL_LEN}"

    python scripts/dpo/run_preference_pipeline.py \
      --adapter-path "${BASE_SFT_ADAPTER}" \
      --base-model "${BASE_MODEL}" \
      --pairs-dir "${JUDGE_GPTOSS_PAIRS_DIR}" \
      --balanced-pairs-dir "${JUDGE_UNION_BALANCED_DIR/_balanced/_gptoss_balanced}" \
      --dpo-output-dir "trained_models/causal/dpo-judge-gptoss" \
      --epochs "${JUDGE_EPOCHS}" \
      --learning-rate "${LEARNING_RATE}" \
      --batch-size "${BATCH_SIZE}" \
      --grad-accum "${GRAD_ACCUM}" \
      --dpo-beta "${JUDGE_BETA}" \
      --attn-implementation "${ATTN_IMPL}" \
      --seed "${SEED}" \
      --wandb-project "${WANDB_PROJECT}" \
      --wandb-run "judge-gptoss-dpo-${GPTOSS_JUDGE_MODEL_SLUG}-beta${JUDGE_BETA}-seed${SEED}" \
      "${PIPELINE_CKPT_ARGS[@]}" \
      "${PIPELINE_RESTART_ARGS[@]}" \
      --skip-steps 1
    ;;

  judge_standalone_dpo)
    # Judge-only condition: rejecteds = bad_match samples only, no hard mislabels.
    # Generates both dpo_pairs.jsonl (bad only) and dpo_pairs_decent.jsonl (bad+decent)
    # so judge_decent_dpo can reuse these pairs without a second generation pass.
    python scripts/dpo/generate_dpo_pairs.py \
      --from-samples "${CANONICAL_SAMPLES}" \
      --adapter-path "${BASE_SFT_ADAPTER}" \
      --base-model "${BASE_MODEL}" \
      --output-dir "${JUDGE_STANDALONE_PAIRS_DIR}" \
      --intent-filter \
      --judge-only \
      --judge-model "${JUDGE_MODEL}" \
      --judge-tensor-parallel "${JUDGE_TENSOR_PARALLEL}" \
      --max-model-len "${MAX_MODEL_LEN}"

    python scripts/dpo/run_preference_pipeline.py \
      --adapter-path "${BASE_SFT_ADAPTER}" \
      --base-model "${BASE_MODEL}" \
      --pairs-dir "${JUDGE_STANDALONE_PAIRS_DIR}" \
      --balanced-pairs-dir "${JUDGE_STANDALONE_BALANCED_DIR}" \
      --dpo-output-dir "${JUDGE_STANDALONE_DPO_OUTPUT}" \
      --epochs "${JUDGE_EPOCHS}" \
      --learning-rate "${LEARNING_RATE}" \
      --batch-size "${BATCH_SIZE}" \
      --grad-accum "${GRAD_ACCUM}" \
      --dpo-beta "${JUDGE_BETA}" \
      --attn-implementation "${ATTN_IMPL}" \
      --seed "${SEED}" \
      --wandb-project "${WANDB_PROJECT}" \
      --wandb-run "judge-standalone-dpo-${JUDGE_MODEL_SLUG}-beta${JUDGE_BETA}-seed${SEED}" \
      "${PIPELINE_CKPT_ARGS[@]}" \
      "${PIPELINE_RESTART_ARGS[@]}" \
      --skip-steps 1
    ;;

  judge_gptoss_standalone_dpo)
    # GPT-OSS judge-only condition: rejecteds = bad_match samples only, no hard mislabels.
    # GPT-OSS analogue of judge_standalone_dpo for a clean standalone comparison.
    GPTOSS_JUDGE_MODEL="${GPTOSS_JUDGE_MODEL:-openai/gpt-oss-120b}"
    GPTOSS_JUDGE_MODEL_SLUG="${GPTOSS_JUDGE_MODEL//\//_}"
    GPTOSS_JUDGE_TP="${GPTOSS_JUDGE_TP:-1}"

    python scripts/dpo/generate_dpo_pairs.py \
      --from-samples "${CANONICAL_SAMPLES}" \
      --adapter-path "${BASE_SFT_ADAPTER}" \
      --base-model "${BASE_MODEL}" \
      --output-dir "${JUDGE_GPTOSS_STANDALONE_PAIRS_DIR}" \
      --intent-filter \
      --judge-only \
      --judge-model "${GPTOSS_JUDGE_MODEL}" \
      --judge-tensor-parallel "${GPTOSS_JUDGE_TP}" \
      --max-model-len "${MAX_MODEL_LEN}"

    python scripts/dpo/run_preference_pipeline.py \
      --adapter-path "${BASE_SFT_ADAPTER}" \
      --base-model "${BASE_MODEL}" \
      --pairs-dir "${JUDGE_GPTOSS_STANDALONE_PAIRS_DIR}" \
      --balanced-pairs-dir "${JUDGE_GPTOSS_STANDALONE_BALANCED_DIR}" \
      --dpo-output-dir "${JUDGE_GPTOSS_STANDALONE_DPO_OUTPUT}" \
      --epochs "${JUDGE_EPOCHS}" \
      --learning-rate "${LEARNING_RATE}" \
      --batch-size "${BATCH_SIZE}" \
      --grad-accum "${GRAD_ACCUM}" \
      --dpo-beta "${JUDGE_BETA}" \
      --attn-implementation "${ATTN_IMPL}" \
      --seed "${SEED}" \
      --wandb-project "${WANDB_PROJECT}" \
      --wandb-run "judge-gptoss-standalone-dpo-${GPTOSS_JUDGE_MODEL_SLUG}-beta${JUDGE_BETA}-seed${SEED}" \
      "${PIPELINE_CKPT_ARGS[@]}" \
      "${PIPELINE_RESTART_ARGS[@]}" \
      --skip-steps 1
    ;;

  judge_decent_dpo)
    # Judge-only condition with bad_match + decent_match rejecteds.
    # Requires judge_standalone_dpo to have run first (reuses its dpo_pairs_decent.jsonl).
    python scripts/dpo/run_preference_pipeline.py \
      --adapter-path "${BASE_SFT_ADAPTER}" \
      --base-model "${BASE_MODEL}" \
      --pairs-dir "${JUDGE_STANDALONE_PAIRS_DIR}" \
      --pairs-filename "dpo_pairs_decent.jsonl" \
      --balanced-pairs-dir "${JUDGE_DECENT_BALANCED_DIR}" \
      --dpo-output-dir "${JUDGE_DECENT_DPO_OUTPUT}" \
      --epochs "${JUDGE_EPOCHS}" \
      --learning-rate "${LEARNING_RATE}" \
      --batch-size "${BATCH_SIZE}" \
      --grad-accum "${GRAD_ACCUM}" \
      --dpo-beta "${JUDGE_BETA}" \
      --attn-implementation "${ATTN_IMPL}" \
      --seed "${SEED}" \
      --wandb-project "${WANDB_PROJECT}" \
      --wandb-run "judge-decent-dpo-${JUDGE_MODEL_SLUG}-beta${JUDGE_BETA}-seed${SEED}" \
      "${PIPELINE_CKPT_ARGS[@]}" \
      "${PIPELINE_RESTART_ARGS[@]}" \
      --skip-steps 1
    ;;

  union_decent_dpo)
    # Union condition with bad_match + decent_match rejecteds (hard ∪ judge decent).
    # Requires judge_dpo to have run first (reuses its dpo_pairs_decent.jsonl).
    python scripts/dpo/run_preference_pipeline.py \
      --adapter-path "${BASE_SFT_ADAPTER}" \
      --base-model "${BASE_MODEL}" \
      --pairs-dir "${JUDGE_PAIRS_DIR}" \
      --pairs-filename "dpo_pairs_decent.jsonl" \
      --balanced-pairs-dir "${UNION_DECENT_BALANCED_DIR}" \
      --dpo-output-dir "${UNION_DECENT_DPO_OUTPUT}" \
      --epochs "${JUDGE_EPOCHS}" \
      --learning-rate "${LEARNING_RATE}" \
      --batch-size "${BATCH_SIZE}" \
      --grad-accum "${GRAD_ACCUM}" \
      --dpo-beta "${JUDGE_BETA}" \
      --attn-implementation "${ATTN_IMPL}" \
      --seed "${SEED}" \
      --wandb-project "${WANDB_PROJECT}" \
      --wandb-run "union-decent-dpo-${JUDGE_MODEL_SLUG}-beta${JUDGE_BETA}-seed${SEED}" \
      "${PIPELINE_CKPT_ARGS[@]}" \
      "${PIPELINE_RESTART_ARGS[@]}" \
      --skip-steps 1
    ;;

  judge_union_dpo)
    # Union of bad_match verdicts from two judge models (gemma + GPT-OSS).
    # No model inference needed — verdicts are loaded from cached parsed_samples.jsonl.
    # Prerequisites: judge_dpo and judge_gptoss must have completed so that
    # judge_verdict fields are saved in their parsed_samples.jsonl.

    JUDGE_PRIMARY_SAMPLES="${JUDGE_PAIRS_DIR}/parsed_samples.jsonl"
    JUDGE_GPTOSS_SAMPLES="${JUDGE_GPTOSS_PAIRS_DIR}/parsed_samples.jsonl"

    if [ ! -f "${JUDGE_PRIMARY_SAMPLES}" ]; then
      echo "ERROR: ${JUDGE_PRIMARY_SAMPLES} not found."
      echo "  Run judge_dpo (gemma) first to generate judge verdicts."
      exit 1
    fi
    if [ ! -f "${JUDGE_GPTOSS_SAMPLES}" ]; then
      echo "ERROR: ${JUDGE_GPTOSS_SAMPLES} not found."
      echo "  Run judge_gptoss first to generate judge verdicts."
      exit 1
    fi

    # Check that judge_verdict is actually present in both files
    python3 -c "
import json, sys
for path in ['${JUDGE_PRIMARY_SAMPLES}', '${JUDGE_GPTOSS_SAMPLES}']:
    lines = open(path).readlines()
    found = sum(1 for l in lines for s in json.loads(l).get('samples', []) if 'judge_verdict' in s)
    if found == 0:
        print(f'ERROR: judge_verdict missing from {path}')
        print('  Re-run the judge stage with the updated code to cache verdicts.')
        sys.exit(1)
    print(f'OK: {path} — {found} samples with judge_verdict')
print('Prerequisite check passed.')
" || exit 1

    # Merge verdicts and build pairs (no model loaded — verdicts already cached)
    python scripts/dpo/generate_dpo_pairs.py \
      --from-samples "${JUDGE_PRIMARY_SAMPLES}" \
      --adapter-path "${BASE_SFT_ADAPTER}" \
      --base-model "${BASE_MODEL}" \
      --output-dir "${JUDGE_UNION_PAIRS_DIR}" \
      --intent-filter \
      --union-judge-dir "${JUDGE_GPTOSS_PAIRS_DIR}" \
      --max-model-len "${MAX_MODEL_LEN}"

    python scripts/dpo/run_preference_pipeline.py \
      --adapter-path "${BASE_SFT_ADAPTER}" \
      --base-model "${BASE_MODEL}" \
      --pairs-dir "${JUDGE_UNION_PAIRS_DIR}" \
      --balanced-pairs-dir "${JUDGE_UNION_BALANCED_DIR}" \
      --dpo-output-dir "${JUDGE_UNION_DPO_OUTPUT}" \
      --epochs "${JUDGE_EPOCHS}" \
      --learning-rate "${LEARNING_RATE}" \
      --batch-size "${BATCH_SIZE}" \
      --grad-accum "${GRAD_ACCUM}" \
      --dpo-beta "${JUDGE_BETA}" \
      --attn-implementation "${ATTN_IMPL}" \
      --seed "${SEED}" \
      --wandb-project "${WANDB_PROJECT}" \
      --wandb-run "judge-union-dpo-${JUDGE_MODEL_SLUG}-beta${JUDGE_BETA}-seed${SEED}" \
      "${PIPELINE_CKPT_ARGS[@]}" \
      "${PIPELINE_RESTART_ARGS[@]}" \
      --skip-steps 1
    ;;

  ood_eval)
    # Run OOD validation (ToxicChat train + AEGIS validation) on a trained DPO adapter.
    # Uses the same eval_ood_validation config as SFT/distillation OOD eval, so results
    # are directly comparable across all model families.
    #
    # Set OOD_EVAL_ADAPTER to the _adapter directory of the condition to evaluate, e.g.:
    #   OOD_EVAL_ADAPTER=trained_models/causal/dpo-hard_adapter
    if [ -z "${OOD_EVAL_ADAPTER}" ]; then
      echo "ERROR: OOD_EVAL_ADAPTER is required for the ood_eval stage."
      echo "  Set it to the _adapter directory of the trained DPO condition, e.g.:"
      echo "    OOD_EVAL_ADAPTER=trained_models/causal/dpo-hard_adapter"
      exit 1
    fi
    ADAPTER_SLUG="${OOD_EVAL_ADAPTER##*/}"   # basename, e.g. dpo-hard_adapter
    python scripts/eval_safety_classifier.py \
      --config-name=eval_ood_validation \
      "finetuned.generation_adapter=${OOD_EVAL_ADAPTER}" \
      "experiment.conditions=[finetuned_generation]" \
      "paths.output_dir=${OOD_EVAL_OUTPUT}/${ADAPTER_SLUG}" \
      "wandb.run_name=ood-val-${ADAPTER_SLUG}" \
      "model.name=${BASE_MODEL}"
    ;;

  ratio_dpo)
    # Additive ratio sweep: all hard pairs + RATIO fraction of judge pairs.
    # Prerequisites: HARD_PAIRS_FILE and JUDGE_PAIRS_FILE must already exist
    # (run canonical + hard_dpo + judge_dpo stages first).
    if [ ! -f "${HARD_PAIRS_FILE}" ]; then
      echo "ERROR: ${HARD_PAIRS_FILE} not found. Run hard_dpo stage first."
      exit 1
    fi
    if [ ! -f "${JUDGE_PAIRS_FILE}" ]; then
      echo "ERROR: ${JUDGE_PAIRS_FILE} not found. Run judge_dpo/judge_standalone_dpo stage first."
      exit 1
    fi

    RATIO_MIXED="${RATIO_PAIRS_DIR}/dpo_pairs.jsonl"
    RATIO_BALANCED="${RATIO_BALANCED_DIR}/dpo_pairs.jsonl"

    # Keep ratio=0.00 exactly comparable to hard_dpo by bypassing the mixer
    # (which shuffles rows) and balancing the canonical hard pairs directly.
    case "${RATIO}" in
      0|0.0|0.00)
        echo "[ratio_dpo] RATIO=${RATIO} -> using hard pairs directly for exact hard_dpo comparability."
        RATIO_MIXED="${HARD_PAIRS_FILE}"
        ;;
      *)
        python scripts/dpo/mix_dpo_pairs.py \
          --hard-pairs  "${HARD_PAIRS_FILE}" \
          --judge-pairs "${JUDGE_PAIRS_FILE}" \
          --ratio       "${RATIO}" \
          --output      "${RATIO_MIXED}" \
          --seed        "${SEED}"
        ;;
    esac

    python scripts/dpo/balance_dpo_pairs.py \
      --input  "${RATIO_MIXED}" \
      --output "${RATIO_BALANCED}" \
      --seed   "${SEED}"

    python scripts/dpo/train_dpo.py \
      --pairs-path   "${RATIO_BALANCED}" \
      --adapter-path "${BASE_SFT_ADAPTER}" \
      --base-model   "${BASE_MODEL}" \
      --output-dir   "${RATIO_DPO_OUTPUT}" \
      --epochs       "${EPOCHS}" \
      --learning-rate "${LEARNING_RATE}" \
      --batch-size   "${BATCH_SIZE}" \
      --gradient-accumulation "${GRAD_ACCUM}" \
      --beta         "${DPO_BETA}" \
      --attn-implementation "${ATTN_IMPL}" \
      --seed         "${SEED}" \
      --wandb-project "${WANDB_PROJECT}" \
      --wandb-run    "ratio-dpo-${RATIO_TAG}-beta${DPO_BETA}-seed${SEED}" \
      "${TRAIN_CKPT_ARGS[@]}"

    python scripts/eval_safety_classifier.py \
      --config-name=dpo/eval_dpo_condition \
      "++finetuned.generation_adapter=${RATIO_DPO_OUTPUT}_adapter" \
      "++paths.output_dir=${RATIO_DPO_OUTPUT}/predictions" \
      "++model.name=${BASE_MODEL}" \
      "++lora.rank=${EVAL_LORA_RANK}"
    ;;

  curriculum_dpo)
    # Continuation-only curriculum:
    # Continue directly from an existing hard-DPO adapter on judge pairs.
    # Reference model remains SFT; policy starts from CURRICULUM_POLICY_ADAPTER.
    JUDGE_BALANCED="${JUDGE_BALANCED_DIR}/dpo_pairs.jsonl"

    if [ ! -f "${JUDGE_BALANCED}" ]; then
      echo "ERROR: ${JUDGE_BALANCED} not found. Run judge_dpo stage first."
      exit 1
    fi
    if [ -z "${CURRICULUM_POLICY_ADAPTER}" ]; then
      echo "ERROR: CURRICULUM_POLICY_ADAPTER is required for curriculum_dpo."
      echo "  Example:"
      echo "    CURRICULUM_POLICY_ADAPTER=trained_models/causal/llama31-8b-k10-e-hard-b0.3-e3-s22_adapter"
      exit 1
    fi
    if [ ! -f "${CURRICULUM_POLICY_ADAPTER}/adapter_config.json" ]; then
      echo "ERROR: ${CURRICULUM_POLICY_ADAPTER}/adapter_config.json not found."
      echo "  CURRICULUM_POLICY_ADAPTER must point to a *_adapter directory."
      exit 1
    fi

    CURR_SAVE_STRATEGY="${DPO_SAVE_STRATEGY}"
    if [ "${CURR_SAVE_STRATEGY}" = "no" ]; then
      CURR_SAVE_STRATEGY="steps"
      echo "[curriculum_dpo] DPO_SAVE_STRATEGY=no -> overriding to steps so checkpoint selection can run."
    fi
    CURR_TRAIN_CKPT_ARGS=(
      --save-strategy "${CURR_SAVE_STRATEGY}"
      --save-total-limit "${DPO_SAVE_TOTAL_LIMIT}"
      --select-best-ood-checkpoint
      --ood-eval-gpu-memory-utilization "${OOD_EVAL_GPU_MEMORY_UTILIZATION}"
    )
    if [ "${CURR_SAVE_STRATEGY}" = "steps" ]; then
      CURR_TRAIN_CKPT_ARGS+=(--save-steps "${DPO_SAVE_STEPS}")
    fi

    echo "[curriculum_dpo] Continuing from existing hard-DPO adapter on judge pairs."
    echo "[curriculum_dpo] Policy adapter: ${CURRICULUM_POLICY_ADAPTER}"
    echo "[curriculum_dpo] Epochs: ${PHASE2_EPOCHS}"
    python scripts/dpo/train_dpo.py \
      --pairs-path     "${JUDGE_BALANCED}" \
      --adapter-path   "${BASE_SFT_ADAPTER}" \
      --policy-adapter "${CURRICULUM_POLICY_ADAPTER}" \
      --base-model     "${BASE_MODEL}" \
      --output-dir     "${CURRICULUM_OUTPUT}" \
      --epochs         "${PHASE2_EPOCHS}" \
      --learning-rate  "${LEARNING_RATE}" \
      --batch-size     "${BATCH_SIZE}" \
      --gradient-accumulation "${GRAD_ACCUM}" \
      --beta           "${DPO_BETA}" \
      --attn-implementation "${ATTN_IMPL}" \
      --seed           "${SEED}" \
      --skip-eval \
      --wandb-project  "${WANDB_PROJECT}" \
      --wandb-run      "curriculum-continue-beta${DPO_BETA}-seed${SEED}" \
      "${CURR_TRAIN_CKPT_ARGS[@]}"

    python scripts/eval_safety_classifier.py \
      --config-name=dpo/eval_dpo_condition \
      "++finetuned.generation_adapter=${CURRICULUM_OUTPUT}_adapter" \
      "++paths.output_dir=${CURRICULUM_OUTPUT}/predictions" \
      "++model.name=${BASE_MODEL}" \
      "++lora.rank=${EVAL_LORA_RANK}"
    ;;

  gemma_canonical)
    # Generate shared T=0.8 samples from Jeremias's Gemma SFT model.
    # Set GEMMA_NO_LORA=1 if GEMMA_SFT_ADAPTER is a merged model (full weights),
    # or leave at 0 if it is a LoRA adapter on top of GEMMA_BASE_MODEL.
    if [ -f "${GEMMA_CANONICAL_SAMPLES}" ]; then
      echo "[SKIP] Gemma canonical samples already exist at ${GEMMA_CANONICAL_SAMPLES}"
      exit 0
    fi
    GEMMA_CANONICAL_OUT_DIR="$(dirname "${GEMMA_CANONICAL_SAMPLES}")"
    GEMMA_NO_LORA_FLAG=""
    if [ "${GEMMA_NO_LORA}" = "1" ]; then
      GEMMA_NO_LORA_FLAG="--no-lora"
      echo "[gemma_canonical] Merged model mode: loading ${GEMMA_SFT_ADAPTER} directly."
      GEMMA_GEN_BASE="${GEMMA_SFT_ADAPTER}"
    else
      echo "[gemma_canonical] LoRA mode: base=${GEMMA_BASE_MODEL}, adapter=${GEMMA_SFT_ADAPTER}."
      GEMMA_GEN_BASE="${GEMMA_BASE_MODEL}"
    fi

    python scripts/dpo/generate_dpo_pairs.py \
      --base-model  "${GEMMA_GEN_BASE}" \
      --adapter-path "${GEMMA_SFT_ADAPTER}" \
      --output-dir  "${GEMMA_CANONICAL_OUT_DIR}" \
      --num-samples "${K_SAMPLES}" \
      --temperature "${TEMPERATURE}" \
      --max-model-len "${MAX_MODEL_LEN}" \
      --seed        "${SEED}" \
      ${GEMMA_NO_LORA_FLAG}
    ;;

  gemma_hard_dpo)
    # Hard-mislabel DPO on Jeremias's Gemma 3 12B SFT model.
    # Uses _load_causal_lm for training (language tower extraction) and
    # --init-new-lora since the SFT adapter may be a merged model.
    # Adjust GEMMA_INIT_NEW_LORA=0 if GEMMA_SFT_ADAPTER is a raw LoRA adapter.
    GEMMA_INIT_NEW_LORA="${GEMMA_INIT_NEW_LORA:-1}"
    GEMMA_INIT_NEW_LORA_FLAG=""
    if [ "${GEMMA_INIT_NEW_LORA}" = "1" ]; then
      GEMMA_INIT_NEW_LORA_FLAG="--init-new-lora"
      GEMMA_TRAIN_BASE="${GEMMA_SFT_ADAPTER}"
      GEMMA_REF_ADAPTER_FLAG=""
    else
      GEMMA_TRAIN_BASE="${GEMMA_BASE_MODEL}"
      GEMMA_REF_ADAPTER_FLAG="--adapter-path ${GEMMA_SFT_ADAPTER}"
    fi

    GEMMA_HARD_PAIRS_FILE="${GEMMA_HARD_PAIRS_DIR}/pairs_wrong_only.jsonl"
    GEMMA_HARD_BALANCED="${GEMMA_HARD_BALANCED_DIR}/dpo_pairs.jsonl"

    if [ ! -f "${GEMMA_HARD_PAIRS_FILE}" ]; then
      # Build hard pairs from Gemma canonical samples
      if [ ! -f "${GEMMA_CANONICAL_SAMPLES}" ]; then
        echo "ERROR: ${GEMMA_CANONICAL_SAMPLES} not found. Run gemma_canonical first."
        exit 1
      fi
      GEMMA_PAIR_NO_LORA_FLAG=""
      GEMMA_PAIR_BASE="${GEMMA_BASE_MODEL}"
      if [ "${GEMMA_NO_LORA}" = "1" ]; then
        GEMMA_PAIR_NO_LORA_FLAG="--no-lora"
        GEMMA_PAIR_BASE="${GEMMA_SFT_ADAPTER}"
      fi
      python scripts/dpo/generate_dpo_pairs.py \
        --from-samples "${GEMMA_CANONICAL_SAMPLES}" \
        --base-model   "${GEMMA_PAIR_BASE}" \
        --adapter-path "${GEMMA_SFT_ADAPTER}" \
        --output-dir   "${GEMMA_HARD_PAIRS_DIR}" \
        --max-model-len "${MAX_MODEL_LEN}" \
        ${GEMMA_PAIR_NO_LORA_FLAG}
    fi

    python scripts/dpo/balance_dpo_pairs.py \
      --input  "${GEMMA_HARD_PAIRS_FILE}" \
      --output "${GEMMA_HARD_BALANCED}" \
      --seed   "${SEED}"

    # shellcheck disable=SC2086
    python scripts/dpo/train_dpo.py \
      --pairs-path   "${GEMMA_HARD_BALANCED}" \
      --base-model   "${GEMMA_TRAIN_BASE}" \
      ${GEMMA_REF_ADAPTER_FLAG} \
      ${GEMMA_INIT_NEW_LORA_FLAG} \
      --output-dir   "${GEMMA_HARD_DPO_OUTPUT}" \
      --epochs       "${EPOCHS}" \
      --learning-rate "${LEARNING_RATE}" \
      --batch-size   "${BATCH_SIZE}" \
      --gradient-accumulation "${GRAD_ACCUM}" \
      --beta         "${DPO_BETA}" \
      --attn-implementation "${ATTN_IMPL}" \
      --seed         "${SEED}" \
      --wandb-project "${WANDB_PROJECT}" \
      --wandb-run    "gemma-hard-dpo-beta${DPO_BETA}-seed${SEED}" \
      "${TRAIN_CKPT_ARGS[@]}"

    # Evaluate on the same base model that the DPO adapter was trained against.
    # In merged-SFT mode this is GEMMA_SFT_ADAPTER; in LoRA mode it's GEMMA_BASE_MODEL.
    GEMMA_EVAL_BASE="${GEMMA_TRAIN_BASE}"
    python scripts/eval_safety_classifier.py \
      --config-name=dpo/eval_dpo_condition \
      "++finetuned.generation_adapter=${GEMMA_HARD_DPO_OUTPUT}_adapter" \
      "++paths.output_dir=${GEMMA_HARD_DPO_OUTPUT}/predictions" \
      "++model.name=${GEMMA_EVAL_BASE}" \
      "++lora.rank=${EVAL_LORA_RANK}"
    ;;

  *)
    echo "ERROR: Unknown STAGE='${STAGE}'"
    exit 2
    ;;
esac

echo ""
echo "Stage ${STAGE} completed."
