import os
import json
import re
import gc
import torch
from tqdm import tqdm

from transformers import (
    AutoTokenizer,
    AutoModelForCausalLM,
    BitsAndBytesConfig,
    EarlyStoppingCallback,
)
from trl import SFTTrainer, SFTConfig
from vllm import LLM, SamplingParams
from vllm.lora.request import LoRARequest

from .preprocessing import preprocess_data
from .data_utils import train_val_test_split, align_tokenizer_with_model, apply_binary_harm_mapping
from .evaluate_generations import compute_and_log_metrics
from .prompt_templates import build_student_prompt

try:
    from peft import LoraConfig, get_peft_model, prepare_model_for_kbit_training
except ImportError:
    LoraConfig = None
    get_peft_model = None
    prepare_model_for_kbit_training = None

def format_prompt(prompt_text, predict_harm=False):
    """
    Format the input prompt for the model.
    
    Args:
        prompt_text: The prompt text (raw text from dataset)
        predict_harm: Whether to include harm prediction task (unused, kept for compatibility)
    
    Returns:
        Formatted prompt string
    """
    return f"{prompt_text}\n"


def format_completion(intent, harm=None, predict_harm=False, classification_only=False):
    """
    Format the completion/target for the model.
    
    Args:
        intent: The intent text
        harm: The harm category (optional)
        predict_harm: Whether to include harm in completion
        classification_only: If True, only output harm label (no intent)
    
    Returns:
        Formatted completion string
    
    Examples:
        - classification_only=True, harm="harmful" -> "harmful"
        - predict_harm=True, intent="get info", harm="safe" -> "Intent: get info; Harm: safe"
        - predict_harm=False -> just the intent
    """
    if classification_only and harm:
        return harm
    
    if predict_harm and harm:
        return f"Intent: {intent}; Harm: {harm}"
    else:
        return intent


def format_completion_with_reasoning(reasoning, harm, intent=None):
    """
    Format the training completion for reasoning trace mode.

    Pipeline: prompt -> Reasoning: ... [-> Intent: ...] -> Prompt harm: ...

    Intent is included only when it is not None.  Harm is normalised from
    WildGuardMix format ("unharmful") to the binary format used by
    safety_experiment.py ("safe") so that downstream evaluation does not need
    a separate remapping step.

    Args:
        reasoning: Reasoning trace text generated for this sample.
        harm:      Ground-truth harm label ("harmful", "unharmful", or "safe").
        intent:    Human-written intent string; omit (None) for classification-only mode.

    Returns:
        Formatted completion string.
    """
    harm_normalised = "safe" if harm and harm.lower() == "unharmful" else (harm or "")
    parts = [f"Reasoning: {reasoning}"]
    if intent:
        parts.append(f"Intent: {intent}")
    parts.append(f"Prompt harm: {harm_normalised}")
    return "\n".join(parts)


def parse_reasoning_output(raw_text, with_intent=False):
    """
    Parse model output produced in reasoning trace format.

    Expected format (same as the training completions above):
        Reasoning: <step-by-step analysis>
        [Intent: <inferred intent>]       <- only in generation mode
        Prompt harm: <harmful|safe>

    Args:
        raw_text:    Raw string generated by the model.
        with_intent: Whether to extract an Intent field.

    Returns:
        (reasoning, intent, predicted_harm)
        intent is None when with_intent=False.
        predicted_harm is "harmful" or "safe" (None if unparseable).
    """
    text = raw_text.strip()

    # Extract Reasoning (up to Intent:, Prompt harm:, or end of string)
    reasoning = ""
    reasoning_match = re.search(
        r'Reasoning:\s*(.+?)(?=Intent:|Prompt harm:|$)', text, re.IGNORECASE | re.DOTALL
    )
    if reasoning_match:
        reasoning = reasoning_match.group(1).strip()

    # Extract Intent (optional)
    intent = None
    if with_intent:
        intent_match = re.search(
            r'Intent:\s*(.+?)(?=Prompt harm:|$)', text, re.IGNORECASE | re.DOTALL
        )
        if intent_match:
            intent = intent_match.group(1).strip()

    # Extract Prompt harm label
    predicted_harm = None
    harm_match = re.search(r'Prompt harm:\s*(harmful|unharmful|safe)', text, re.IGNORECASE)
    if harm_match:
        raw_harm = harm_match.group(1).lower()
        predicted_harm = "safe" if raw_harm == "unharmful" else raw_harm

    return reasoning, intent, predicted_harm


def load_reasoning_traces_dataset(data_cfg):
    """
    Load reasoning traces from a parsed_results.json file produced by
    generate_reasoning_traces.py and return a HuggingFace Dataset suitable
    for SFT training.

    The JSON file contains one record per (sample, condition) pair.  This
    function filters to a single condition so the training signal is consistent:

    * "without_intent" — reasoning conditioned on ground-truth harm label, no
      intent in the completion.  Good for training a classification-only model.
    * "with_intent"    — same but the human-written intent is also present in
      both the reasoning context and the training completion.  Use this to
      train a generation model (reasoning + intent + harm).

    Only records with a non-empty reasoning trace AND a resolvable binary harm
    label are kept.  The harm label is normalised to "harmful"/"safe" so that
    the output is directly compatible with safety_experiment.py evaluation.

    Required config keys (under ``data``):
        reasoning_traces_path       -- path to parsed_results.json
        reasoning_traces_condition  -- "without_intent" or "with_intent"

    Returns:
        HuggingFace Dataset with columns: id, prompt, intent, harm_label, reasoning
    """
    from datasets import Dataset
    from .data_utils import map_harm_to_binary

    traces_path = data_cfg.get("reasoning_traces_path")
    condition = data_cfg.get("reasoning_traces_condition", "without_intent")

    if not traces_path:
        raise ValueError(
            "data.reasoning_traces_path must be set when use_reasoning_traces=True"
        )

    print(f"Loading reasoning traces from: {traces_path}")
    print(f"  Condition filter: {condition}")

    with open(traces_path) as f:
        records = json.load(f)

    available_conditions = list({r.get("condition") for r in records})
    filtered = []
    for rec in records:
        if rec.get("condition") != condition:
            continue
        reasoning = rec.get("reasoning", "").strip()
        harm_raw = rec.get("ground_truth", {}).get("prompt_harm_label")
        harm_binary = map_harm_to_binary(harm_raw)
        if not reasoning or harm_binary is None:
            continue
        filtered.append({
            "id": str(rec.get("wildguard_id", "")),
            "prompt": rec.get("prompt", ""),
            "intent": rec.get("ground_truth", {}).get("intent", ""),
            "harm_label": harm_binary,   # "harmful" or "safe"
            "reasoning": reasoning,
        })

    if not filtered:
        raise ValueError(
            f"No valid reasoning traces found for condition '{condition}' in "
            f"{traces_path}.  Available conditions: {available_conditions}"
        )

    print(f"  Loaded {len(filtered)} examples (condition='{condition}')")
    return Dataset.from_list(filtered)


def save_preds_causal(model_name, llm, lora_request, tokenizer, eval_dataset, split_name, config, max_length=256):
    """
    Generate predictions using VLLM for faster inference.
    
    Args:
        model_name: Name of the model (for file naming)
        llm: Initialized VLLM LLM instance
        lora_request: Initialized VLLM LoRARequest instance (or None)
        tokenizer: Tokenizer for formatting prompts
        eval_dataset: Dataset to generate predictions on
        split_name: Name of the split (e.g., "val", "test")
        config: Configuration dictionary
        max_length: Maximum input length for tokenization
    """
    paths_cfg = config.get("paths", {})
    gen_cfg = config.get("generation", {})
    data_cfg = config.get("data", {})
    predict_harm = data_cfg.get("predict_harm", False)
    classification_only = data_cfg.get("classification_only", False)
    use_reasoning_traces = data_cfg.get("use_reasoning_traces", False)
    # with_intent is derived from the trace condition: "with_intent" condition -> generation mode
    with_intent = data_cfg.get("reasoning_traces_condition", "without_intent") == "with_intent"

    # Use different directory based on mode
    if use_reasoning_traces:
        suffix = "generation" if with_intent else "classification"
        base_pred_dir = paths_cfg.get("predictions_dir", "predictions_causal")
        base_pred_dir = base_pred_dir.replace("predictions", f"predictions_reasoning_{suffix}")
    elif classification_only:
        base_pred_dir = paths_cfg.get("predictions_dir", "predictions_causal")
        base_pred_dir = base_pred_dir.replace("predictions", "predictions_classification")
    elif predict_harm:
        base_pred_dir = paths_cfg.get("predictions_dir", "predictions_causal")
        base_pred_dir = base_pred_dir.replace("predictions", "predictions_with_harm")
    else:
        base_pred_dir = paths_cfg.get("predictions_dir", "predictions_causal")
    
    os.makedirs(base_pred_dir, exist_ok=True)

    filename = f"{model_name.replace('/', '_')}_{split_name}.jsonl"
    full_path = os.path.join(base_pred_dir, filename)

    # Generation settings
    gen_max_new_tokens = int(gen_cfg.get("max_new_tokens", 32))
    num_beams = int(gen_cfg.get("num_beams", 1))
    do_sample = bool(gen_cfg.get("do_sample", False))
    
    # Sampling parameters
    temperature = float(gen_cfg.get("temperature", 1.0))
    top_p = float(gen_cfg.get("top_p", 1.0))
    top_k = int(gen_cfg.get("top_k", 50))
    
    # Build sampling parameters for VLLM
    sampling_params = SamplingParams(
        max_tokens=gen_max_new_tokens,
        temperature=temperature if do_sample else 0.0,
        top_p=top_p if do_sample else 1.0,
        top_k=top_k if do_sample else -1,
        skip_special_tokens=True,
    )
    
    # Prepare all prompts
    examples = list(eval_dataset)
    prompt_texts = [ex['prompt'] for ex in examples]
    
    # Collect all predictions and references for metric computation
    all_preds = []
    all_refs = []

    # Generate all predictions with VLLM (handles batching internally)
    print(f"Generating {split_name} predictions with VLLM...")
    outputs = llm.generate(prompt_texts, sampling_params, lora_request=lora_request)
    
    # Process and save results
    with open(full_path, "w", encoding="utf-8") as f:
        for ex, output in zip(examples, outputs):
            generated_text = output.outputs[0].text.strip()

            if use_reasoning_traces:
                # Reasoning traces mode: parse Reasoning / [Intent] / Prompt harm
                # Output format mirrors safety_experiment.py's zeroshot_cot_* conditions
                # so that the same analysis notebooks and evaluation scripts work.
                reasoning, generated_intent, predicted_harm = parse_reasoning_output(
                    generated_text, with_intent=with_intent
                )
                true_harm = ex.get("harm_label")   # already binary: "harmful"/"safe"
                condition_name = (
                    "finetuned_reasoning_generation"
                    if with_intent
                    else "finetuned_reasoning_classification"
                )
                json_line = {
                    "id": ex["id"],
                    "prompt": ex["prompt"],
                    "true_harm": true_harm,
                    "true_harm_binary": true_harm,
                    "predicted_harm": predicted_harm,
                    "reasoning": reasoning,
                    "raw_generation": generated_text,
                    "condition": condition_name,
                }
                if with_intent:
                    json_line["true_intent"] = ex.get("intent")
                    json_line["generated_intent"] = generated_intent
                all_refs.append(true_harm or "")
                all_preds.append(predicted_harm or "")
            else:
                # Existing modes
                harm = ex.get("Annotator Harm") if (predict_harm or classification_only) else None
                true_formatted = format_completion(
                    ex["intent"], harm, predict_harm, classification_only
                )
                all_preds.append(generated_text)
                all_refs.append(true_formatted)

                if classification_only:
                    json_line = {
                        "id": ex["id"],
                        "prompt": ex["prompt"],
                        "true_harm": harm,
                        "pred_harm": generated_text,
                    }
                else:
                    json_line = {
                        "id": ex["id"],
                        "prompt": ex["prompt"],
                        "true_intent": true_formatted,
                        "generated_intent": generated_text,
                    }
            
            f.write(json.dumps(json_line, ensure_ascii=False) + "\n")

    print(f"Saved {split_name} predictions to {full_path}")
    return all_refs, all_preds


def setup_causal_model_and_tokenizer(config):
    """
    Set up tokenizer and model for causal LM training.

    - If config['peft']['use_lora'] is False or missing:
        → standard full fine-tuning.
    - If True:
        → load model in 4-bit and wrap with LoRA (QLoRA-style).

    Returns:
        tokenizer, model, is_peft
    """
    model_cfg = config.get("model", {})
    peft_cfg = config.get("peft", {})
    quant_cfg = config.get("quantization", {})
    model_name = model_cfg["name"]

    use_lora = bool(peft_cfg.get("use_lora", False))
    
    tokenizer = AutoTokenizer.from_pretrained(model_name)
    tokenizer.padding_side = 'left'

    if not use_lora:
        attn_implementation = model_cfg.get("attn_implementation", "flash_attention_2")
        model = AutoModelForCausalLM.from_pretrained(
            model_name,
            attn_implementation=attn_implementation,
            dtype=torch.bfloat16
        )
        model.config.use_cache = False
        align_tokenizer_with_model(tokenizer, model)
        return tokenizer, model, False

    # === QLoRA path ===
    if BitsAndBytesConfig is None or LoraConfig is None or get_peft_model is None:
        raise ImportError(
            "QLoRA mode requested but `bitsandbytes` and/or `peft` are not installed.\n"
            "Install them with: pip install bitsandbytes peft"
        )

    # 4-bit quantization config
    load_in_4bit = bool(quant_cfg.get("load_in_4bit", True))
    bnb_4bit_use_double_quant = bool(quant_cfg.get("bnb_4bit_use_double_quant", True))
    bnb_4bit_quant_type = quant_cfg.get("bnb_4bit_quant_type", "nf4")
    compute_dtype_str = quant_cfg.get("bnb_4bit_compute_dtype", "bfloat16")
    compute_dtype = getattr(torch, compute_dtype_str, torch.bfloat16)

    bnb_config = BitsAndBytesConfig(
        load_in_4bit=load_in_4bit,
        bnb_4bit_use_double_quant=bnb_4bit_use_double_quant,
        bnb_4bit_quant_type=bnb_4bit_quant_type,
        bnb_4bit_compute_dtype=compute_dtype,
    )

    trust_remote_code = bool(model_cfg.get("trust_remote_code", False))
    attn_implementation = model_cfg.get("attn_implementation", "flash_attention_2")
    model = AutoModelForCausalLM.from_pretrained(
        model_name,
        quantization_config=bnb_config,
        device_map="auto",
        trust_remote_code=trust_remote_code,
        attn_implementation=attn_implementation,
        dtype=compute_dtype,
    )

    model.config.use_cache = False
    model.gradient_checkpointing_enable()

    # Prepare for k-bit training
    model = prepare_model_for_kbit_training(model)

    # LoRA config
    lora_r = int(peft_cfg.get("lora_rank", 16))
    lora_alpha = int(peft_cfg.get("lora_alpha", 32))
    lora_dropout = float(peft_cfg.get("lora_dropout", 0.05))
    bias = peft_cfg.get("bias", "none")

    default_target_modules = ["q_proj", "k_proj", "v_proj", "o_proj"]
    target_modules = peft_cfg.get("target_modules", default_target_modules)

    lora_config = LoraConfig(
        r=lora_r,
        lora_alpha=lora_alpha,
        lora_dropout=lora_dropout,
        bias=bias,
        target_modules=target_modules,
        task_type="CAUSAL_LM",
    )

    model = get_peft_model(model, lora_config)
    align_tokenizer_with_model(tokenizer, model)

    model.print_trainable_parameters()

    return tokenizer, model, True


def prepare_training_arguments(config, is_peft=False, num_train_samples=None):
    """
    Extract and prepare training arguments from config.
    """
    train_cfg = config.get("training", {})
    paths_cfg = config.get("paths", {})
    model_cfg = config.get("model", {})
    
    model_name = model_cfg["name"]
    out_name = model_name.replace("/", "_")
    
    output_dir = paths_cfg.get("output_dir", f"./train_results/causal/{out_name}")
    logs_dir = paths_cfg.get("logs_dir", f"./logs/causal/{out_name}")
    
    epochs = train_cfg.get("epochs", 8)
    lr = train_cfg.get("learning_rate", 5e-5)
    batch_size = train_cfg.get("batch_size", 8)
    weight_decay = train_cfg.get("weight_decay", 0.01)
    grad_accum = train_cfg.get("gradient_accumulation", 1)
    
    use_fp16 = train_cfg.get("fp16", False) and torch.cuda.is_available()
    use_bf16 = train_cfg.get("bf16", False) and torch.cuda.is_available()
    
    if use_fp16 and use_bf16:
        use_fp16 = False
    
    default_optim = "paged_adamw_8bit"
    optim_name = train_cfg.get("optim", default_optim)
    
    adam_beta1 = train_cfg.get("adam_beta1", None)
    adam_beta2 = train_cfg.get("adam_beta2", None)
    
    torch_compile = train_cfg.get("torch_compile", True)
    gradient_checkpointing = train_cfg.get("gradient_checkpointing", True)
    lr_scheduler_type = train_cfg.get("lr_scheduler_type", "cosine")
    warmup_ratio = train_cfg.get("warmup_ratio", 0.1)
    padding_free = train_cfg.get("padding_free", False)
    max_length = model_cfg.get("max_length_causal", 512)
    
    wandb_cfg = config.get("wandb", {})
    report_to = "wandb" if wandb_cfg.get("enabled", False) else "none"
    run_name = wandb_cfg.get("run_name", None)
    
    training_args = {
        "output_dir": output_dir,
        "eval_strategy": "epoch",
        "save_strategy": "epoch",
        "learning_rate": lr,
        "per_device_train_batch_size": batch_size,
        "per_device_eval_batch_size": batch_size,
        "gradient_accumulation_steps": grad_accum,
        "num_train_epochs": epochs,
        "weight_decay": weight_decay,
        "save_total_limit": 2,
        "logging_dir": logs_dir,
        "load_best_model_at_end": True,
        "metric_for_best_model": "eval_loss",
        "fp16": use_fp16,
        "bf16": use_bf16,
        "optim": optim_name,
        "torch_compile": torch_compile,
        "gradient_checkpointing": gradient_checkpointing,
        "lr_scheduler_type": lr_scheduler_type,
        "warmup_ratio": warmup_ratio,
        "report_to": report_to,
        "run_name": run_name,
        "padding_free": padding_free,
        "completion_only_loss": True,
        "remove_unused_columns": False,
        "max_length": max_length,
    }
    
    if adam_beta1 is not None:
        training_args["adam_beta1"] = adam_beta1
    if adam_beta2 is not None:
        training_args["adam_beta2"] = adam_beta2
    
    return training_args


def run_causal_flow(config):
    model_cfg = config.get("model", {})
    paths_cfg = config.get("paths", {})
    train_cfg = config.get("training", {})
    model_name = model_cfg["name"]
    max_length = model_cfg.get("max_length_causal", 256)
    
    skip_training = bool(train_cfg.get("skip_training", False))
    
    # Get data configuration
    data_cfg = config.get("data", {})
    predict_harm = data_cfg.get("predict_harm", False)
    binary_harm_mapping = data_cfg.get("binary_harm_mapping", True)
    classification_only = data_cfg.get("classification_only", False)
    use_reasoning_traces = data_cfg.get("use_reasoning_traces", False)
    # with_intent is derived from the trace condition name: "with_intent" -> generation mode
    with_intent = data_cfg.get("reasoning_traces_condition", "without_intent") == "with_intent"

    # Log the training mode
    if use_reasoning_traces:
        rt_condition = data_cfg.get("reasoning_traces_condition", "without_intent")
        print("=" * 60)
        if with_intent:
            print("REASONING TRACES MODE (generation: reasoning + intent + harm)")
            print("Training format: prompt -> Reasoning: ... / Intent: ... / Prompt harm: ...")
        else:
            print("REASONING TRACES MODE (classification: reasoning + harm)")
            print("Training format: prompt -> Reasoning: ... / Prompt harm: ...")
        print(f"Source condition: {rt_condition}")
        print(f"Traces path:      {data_cfg.get('reasoning_traces_path', '(not set)')}")
        print("=" * 60)
    elif classification_only:
        print("=" * 60)
        print("CLASSIFICATION-ONLY MODE")
        print("Training format: prompt -> harm label (e.g., 'harmful' or 'safe')")
        print("=" * 60)
    elif predict_harm:
        print("=" * 60)
        print("GENERATION MODE (with harm)")
        print("Training format: prompt -> Intent: {intent}; Harm: {harm}")
        print("=" * 60)
    else:
        print("=" * 60)
        print("GENERATION MODE (intent only)")
        print("Training format: prompt -> intent")
        print("=" * 60)

    if use_reasoning_traces:
        # Load pre-generated reasoning traces as training data.
        # Each example already has a reasoning field and a binary harm_label;
        # intent is available for the "with_intent" condition.
        raw_dataset = load_reasoning_traces_dataset(data_cfg)

        def create_prompt_completion(examples):
            # Use the shared student prompt template: preamble + taxonomy + output format
            # so that training and inference see the same input structure.
            prompts = [
                build_student_prompt(p, with_intent=with_intent) + "\n"
                for p in examples["prompt"]
            ]
            intents = examples["intent"] if with_intent else [None] * len(examples["prompt"])
            completions = [
                format_completion_with_reasoning(r, h, i)
                for r, h, i in zip(examples["reasoning"], examples["harm_label"], intents)
            ]
            return {"prompt": prompts, "completion": completions}
    else:
        # Load and prepare dataset
        print("Loading dataset with preprocess_data()...")
        raw_dataset = preprocess_data()
        print("Dataset size:", len(raw_dataset))

        # Apply binary harm mapping if enabled
        raw_dataset = apply_binary_harm_mapping(raw_dataset, binary_harm_mapping)

        def create_prompt_completion(examples):
            prompts = [format_prompt(p, predict_harm) for p in examples["prompt"]]

            if predict_harm:
                harms = examples.get("Annotator Harm", [None] * len(examples["prompt"]))
                completions = [
                    format_completion(i, h, predict_harm, classification_only)
                    for i, h in zip(examples["intent"], harms)
                ]
            else:
                completions = [
                    format_completion(i, None, predict_harm, classification_only)
                    for i in examples["intent"]
                ]

            return {"prompt": prompts, "completion": completions}

    dataset_with_cols = raw_dataset.map(
        create_prompt_completion,
        batched=True,
    )
    
    # Print example of training data
    print("\n" + "=" * 60)
    print("EXAMPLE TRAINING DATA:")
    print("=" * 60)
    example = dataset_with_cols[0]
    print("── PROMPT ──")
    print(example["prompt"])
    print("── COMPLETION ──")
    print(example["completion"])
    print("=" * 60 + "\n")
    
    train_dataset, val_dataset, test_dataset = train_val_test_split(
        dataset_with_cols, config
    )
    
    if skip_training:
        print("Skipping training (skip_training=True)")
        model_save_dir = paths_cfg.get(
            "model_save_dir",
            f"./trained_models/causal/{model_name}-model",
        )
        print(f"Loading pre-trained model from {model_save_dir}")
        tokenizer = AutoTokenizer.from_pretrained(model_save_dir)
    else:
        tokenizer, model, is_peft = setup_causal_model_and_tokenizer(config)

        if not is_peft:
            device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
            model.to(device)

        training_args = SFTConfig(**prepare_training_arguments(config, is_peft, len(train_dataset)))

        early_stopping = EarlyStoppingCallback(
            early_stopping_patience=1,
            early_stopping_threshold=0.0,
        )

        trainer = SFTTrainer(
            model=model,
            args=training_args,
            train_dataset=train_dataset,
            eval_dataset=val_dataset,
            processing_class=tokenizer,
            callbacks=[early_stopping],
        )

        trainer.evaluate()
        trainer.train()

        model_save_dir = paths_cfg.get(
            "model_save_dir",
            f"./trained_models/causal/{model_name}-model",
        )
        if is_peft:
            print("Saving LoRA adapter for VLLM...")
            adapter_dir = model_save_dir + "_adapter"
            os.makedirs(adapter_dir, exist_ok=True)
            trainer.save_model(adapter_dir)
            print(f"LoRA adapter saved to {adapter_dir}")
            tokenizer.save_pretrained(adapter_dir)
        else:
            os.makedirs(model_save_dir, exist_ok=True)
            trainer.save_model(model_save_dir)
            tokenizer.save_pretrained(model_save_dir)
            print(f"Model and tokenizer saved to {model_save_dir}")

        eval_results = trainer.evaluate()
        print(f"[Causal LM] Validation loss: {eval_results['eval_loss']}")

        del model
        del trainer
        del train_dataset
        
        torch.cuda.empty_cache()
        gc.collect()
        torch.cuda.empty_cache()
        torch.cuda.reset_peak_memory_stats()
        torch.cuda.reset_accumulated_memory_stats()
        
        if torch.cuda.is_available():
            allocated = torch.cuda.memory_allocated(0) / 1024**3
            reserved = torch.cuda.memory_reserved(0) / 1024**3
            print(f"GPU Memory after cleanup: {allocated:.2f} GiB allocated, {reserved:.2f} GiB reserved")
        
        print("Freed PyTorch model from GPU memory")

    skip_vllm_eval = bool(train_cfg.get("skip_vllm_eval", False))
    if skip_vllm_eval:
        print("Skipping post-training vLLM evaluation (skip_vllm_eval=True)")
        return

    # Determine paths for VLLM loading
    if skip_training:
        adapter_dir = model_save_dir + "_adapter"
        if os.path.exists(adapter_dir):
            base_model_path = model_name
            adapter_path = adapter_dir
            print(f"Using LoRA adapter from {adapter_path} with base model {base_model_path}")
        else:
            base_model_path = model_save_dir
            adapter_path = None
            print(f"Using full model from {base_model_path}")
    else:
        if is_peft:
            base_model_path = model_name
            adapter_path = model_save_dir + "_adapter"
            print(f"Using LoRA adapter from {adapter_path} with base model {base_model_path}")
        else:
            base_model_path = model_save_dir
            adapter_path = None
            print(f"Using full model from {base_model_path}")

    # Initialize VLLM once
    peft_cfg = config.get("peft", {})
    if adapter_path:
        max_lora_rank = peft_cfg.get("lora_rank", 16)
        print(f"Loading model with VLLM and LoRA from {base_model_path} and {adapter_path}...")
        llm = LLM(
            model=base_model_path, 
            enable_lora=True, 
            max_lora_rank=max_lora_rank, 
            max_loras=1,
            limit_mm_per_prompt={"image": 0},
            gpu_memory_utilization=0.90,
            max_model_len=2048,
            dtype="bfloat16",
            enforce_eager=True
        )
        lora_request = LoRARequest("intent_lora", 1, adapter_path)
    else:
        print(f"Loading model with VLLM from {base_model_path}...")
        llm = LLM(
            model=base_model_path, 
            limit_mm_per_prompt={"image": 0},
            gpu_memory_utilization=0.90,
            max_model_len=2048,
            dtype="bfloat16",
            enforce_eager=True
        )
        lora_request = None

    # Generate predictions using VLLM
    val_refs, val_preds = save_preds_causal(
        model_name, llm, lora_request, tokenizer, val_dataset, "val", config,
        max_length=max_length,
    )
    test_refs, test_preds = save_preds_causal(
        model_name, llm, lora_request, tokenizer, test_dataset, "test", config,
        max_length=max_length,
    )
    
    del llm
    
    # Compute and log metrics
    compute_and_log_metrics(val_refs, val_preds, split_name="val")